# Generated by Django 6.1 on 2026-09-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='categoria',
            field=models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('INSTALACIONES', 'Instalaciones')], default='MANTENIMIENTO', max_length=20),
        ),
    ]
